// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SummaryCmp.Web.Data;

#nullable disable

namespace SummaryCmp.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119144201_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SummaryCmp.Web.Data.Entities.ComparisonSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRanked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SampleFileName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComparisonSessions");
                });

            modelBuilder.Entity("SummaryCmp.Web.Data.Entities.ProviderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderKey", "ModelId")
                        .IsUnique();

                    b.ToTable("ProviderModels");
                });

            modelBuilder.Entity("SummaryCmp.Web.Data.Entities.SummaryResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProviderModelId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserRank")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderModelId");

                    b.HasIndex("SessionId");

                    b.ToTable("SummaryResults");
                });

            modelBuilder.Entity("SummaryCmp.Web.Data.Entities.SummaryResult", b =>
                {
                    b.HasOne("SummaryCmp.Web.Data.Entities.ProviderModel", "ProviderModel")
                        .WithMany("SummaryResults")
                        .HasForeignKey("ProviderModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SummaryCmp.Web.Data.Entities.ComparisonSession", "Session")
                        .WithMany("SummaryResults")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProviderModel");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("SummaryCmp.Web.Data.Entities.ComparisonSession", b =>
                {
                    b.Navigation("SummaryResults");
                });

            modelBuilder.Entity("SummaryCmp.Web.Data.Entities.ProviderModel", b =>
                {
                    b.Navigation("SummaryResults");
                });
#pragma warning restore 612, 618
        }
    }
}
